export const MEASUREMENT_TYPES = {
  LENGTH: 'LENGTH',
  WEIGHT: 'WEIGHT',
  VOLUME: 'VOLUME',
  TEMPERATURE: 'TEMPERATURE'
}

export const UNITS_BY_TYPE = {
  LENGTH: ['FEET', 'INCHES', 'YARDS', 'CENTIMETERS'],
  WEIGHT: ['GRAM', 'KILOGRAM', 'POUND'],
  VOLUME: ['LITRE', 'MILLILITRE', 'GALLON'],
  TEMPERATURE: ['CELSIUS', 'FAHRENHEIT', 'KELVIN']
}

export const ALLOWED_OPERATIONS = {
  LENGTH: ['COMPARE', 'CONVERT', 'ADD', 'SUBTRACT', 'DIVIDE'],
  WEIGHT: ['COMPARE', 'CONVERT', 'ADD', 'SUBTRACT', 'DIVIDE'],
  VOLUME: ['COMPARE', 'CONVERT', 'ADD', 'SUBTRACT', 'DIVIDE'],
  TEMPERATURE: ['COMPARE', 'CONVERT']
}
